[General]

# === Global simulation settings ===

network = Scenario2
sim-time-limit = 10s

# output-vector-file = results/Scenario2-WithoutBER-${runnumber}.vec
# output-scalar-file = results/Scenario2-WithoutBER-${runnumber}.sca

# output-vector-file = results/Scenario2-WithBER-${runnumber}.vec
# output-scalar-file = results/Scenario2-WithBER-${runnumber}.sca

# === Network applications configuration ===

# === LD1 transmitting application ===
*.ld1.appCount = 1
*.ld1.app[0].name = "LD1 --> CU"
*.ld1.app[0].srcAddr = "0A:00:00:00:00:00"
*.ld1.app[0].destAddr = "0A:00:00:00:02:00"
*.ld1.app[0].startTime = 1us
*.ld1.app[0].period = 1.4ms
*.ld1.app[0].payloadSize = 1300B
*.ld1.app[0].burstSize = 2
*.ld1.app[0].vlanid = 1
*.ld1.app[0].pcp = 5
*.ld1.controller.mac.vlans = [1]
*.ld1.controller.encap.address = "0A:00:00:00:00:00"

# === LD2 transmitting application ===
*.ld2.appCount = 1
*.ld2.app[0].name = "LD2 --> CU"
*.ld2.app[0].srcAddr = "0A:00:00:00:00:01"
*.ld2.app[0].destAddr = "0A:00:00:00:02:00"
*.ld2.app[0].startTime = 1us
*.ld2.app[0].period = 1.4ms
*.ld2.app[0].payloadSize = 1300B
*.ld2.app[0].burstSize = 2
*.ld2.app[0].vlanid = 2
*.ld2.app[0].pcp = 5
*.ld2.controller.mac.vlans = [2]
*.ld2.controller.encap.address = "0A:00:00:00:00:01"

# === ME transmitting applications ===
*.me.appCount = 6
*.me.app[0].name = "ME --> S1"
*.me.app[0].srcAddr = "0A:00:00:00:03:00"
*.me.app[0].destAddr = "0A:00:00:00:04:00"
*.me.app[0].startTime = 1us
*.me.app[0].period = 250us
*.me.app[0].payloadSize = 80B
*.me.app[0].burstSize = 1
*.me.app[0].vlanid = 3
*.me.app[0].pcp = 7
*.me.app[1].name = "ME --> S2"
*.me.app[1].srcAddr = "0A:00:00:00:03:00"
*.me.app[1].destAddr = "0A:00:00:00:04:01"
*.me.app[1].startTime = 1us
*.me.app[1].period = 250us
*.me.app[1].payloadSize = 80B
*.me.app[1].burstSize = 1
*.me.app[1].vlanid = 4
*.me.app[1].pcp = 7
*.me.app[2].name = "ME --> S3"
*.me.app[2].srcAddr = "0A:00:00:00:03:00"
*.me.app[2].destAddr = "0A:00:00:00:04:02"
*.me.app[2].startTime = 1us
*.me.app[2].period = 250us
*.me.app[2].payloadSize = 80B
*.me.app[2].burstSize = 1
*.me.app[2].vlanid = 5
*.me.app[2].pcp = 7
*.me.app[3].name = "ME --> S4"
*.me.app[3].srcAddr = "0A:00:00:00:03:00"
*.me.app[3].destAddr = "0A:00:00:00:04:03"
*.me.app[3].startTime = 1us
*.me.app[3].period = 250us
*.me.app[3].payloadSize = 80B
*.me.app[3].burstSize = 1
*.me.app[3].vlanid = 6
*.me.app[3].pcp = 7
*.me.app[4].name = "ME --> RS1"
*.me.app[4].srcAddr = "0A:00:00:00:03:00"
*.me.app[4].destAddr = "0A:00:00:00:08:00"
*.me.app[4].startTime = 1us
*.me.app[4].period = 33.33ms
*.me.app[4].payloadSize = 178500B
*.me.app[4].burstSize = 357
*.me.app[4].vlanid = 13
*.me.app[4].pcp = 2
*.me.app[5].name = "ME --> RS2"
*.me.app[5].srcAddr = "0A:00:00:00:03:00"
*.me.app[5].destAddr = "0A:00:00:00:08:01"
*.me.app[5].startTime = 1us
*.me.app[5].period = 33.33ms
*.me.app[5].payloadSize = 178500B
*.me.app[5].burstSize = 357
*.me.app[5].vlanid = 14
*.me.app[5].pcp = 2
*.me.controller.mac.vlans = [3,4,5,6,13,14]
*.me.controller.encap.address = "0A:00:00:00:03:00"

# === US1 transmitting application ===
*.us1.appCount = 1
*.us1.app[0].name = "US1 --> CU"
*.us1.app[0].srcAddr = "0A:00:00:00:01:00"
*.us1.app[0].destAddr = "0A:00:00:00:02:00"
*.us1.app[0].startTime = 1us
*.us1.app[0].period = 100ms
*.us1.app[0].payloadSize = 188B
*.us1.app[0].burstSize = 1
*.us1.app[0].vlanid = 7
*.us1.app[0].pcp = 1
*.us1.controller.mac.vlans = [7]
*.us1.controller.encap.address = "0A:00:00:00:01:00"

# === US2 transmitting application ===
*.us2.appCount = 1
*.us2.app[0].name = "US2 --> CU"
*.us2.app[0].srcAddr = "0A:00:00:00:01:01"
*.us2.app[0].destAddr = "0A:00:00:00:02:00"
*.us2.app[0].startTime = 1us
*.us2.app[0].period = 100ms
*.us2.app[0].payloadSize = 188B
*.us2.app[0].burstSize = 1
*.us2.app[0].vlanid = 8
*.us2.app[0].pcp = 1
*.us2.controller.mac.vlans = [8]
*.us2.controller.encap.address = "0A:00:00:00:01:01"

# === US3 transmitting application ===
*.us3.appCount = 1
*.us3.app[0].name = "US3 --> CU"
*.us3.app[0].srcAddr = "0A:00:00:00:01:02"
*.us3.app[0].destAddr = "0A:00:00:00:02:00"
*.us3.app[0].startTime = 1us
*.us3.app[0].period = 100ms
*.us3.app[0].payloadSize = 188B
*.us3.app[0].burstSize = 1
*.us3.app[0].vlanid = 9
*.us3.app[0].pcp = 1
*.us3.controller.mac.vlans = [9]
*.us3.controller.encap.address = "0A:00:00:00:01:02"

# === US4 transmitting application ===
*.us4.appCount = 1
*.us4.app[0].name = "US4 --> CU"
*.us4.app[0].srcAddr = "0A:00:00:00:01:03"
*.us4.app[0].destAddr = "0A:00:00:00:02:00"
*.us4.app[0].startTime = 1us
*.us4.app[0].period = 100ms
*.us4.app[0].payloadSize = 188B
*.us4.app[0].burstSize = 1
*.us4.app[0].vlanid = 10
*.us4.app[0].pcp = 1
*.us4.controller.mac.vlans = [10]
*.us4.controller.encap.address = "0A:00:00:00:01:03"

# === CU applicationa ===
# === Transmitting ===
*.cu.appCount = 8
*.cu.app[0].name = "CU --> HU"
*.cu.app[0].srcAddr = "0A:00:00:00:02:00"
*.cu.app[0].destAddr = "0A:00:00:00:07:00"
*.cu.app[0].startTime = 1us
*.cu.app[0].period = 10ms
*.cu.app[0].payloadSize = 10500B
*.cu.app[0].burstSize = 12
*.cu.app[0].vlanid = 11
*.cu.app[0].pcp = 4
# === Receiving ===
*.cu.app[1].name = "LD1 --> CU"
*.cu.app[1].srcAddr = "0A:00:00:00:00:00"
*.cu.app[2].name = "LD2 --> CU"
*.cu.app[2].srcAddr = "0A:00:00:00:00:01"
*.cu.app[3].name = "US1 --> CU"
*.cu.app[3].srcAddr = "0A:00:00:00:01:00"
*.cu.app[4].name = "US2 --> CU"
*.cu.app[4].srcAddr = "0A:00:00:00:01:01"
*.cu.app[5].name = "US3 --> CU"
*.cu.app[5].srcAddr = "0A:00:00:00:01:02"
*.cu.app[6].name = "US4 --> CU"
*.cu.app[6].srcAddr = "0A:00:00:00:01:03"
*.cu.app[7].name = "TLM --> CU"
*.cu.app[7].srcAddr = "0A:00:00:00:09:00"
*.cu.controller.mac.vlans = [11]
*.cu.controller.encap.address = "0A:00:00:00:02:00"

# === CM1 transmitting application ===
*.cm1.appCount = 1
*.cm1.app[0].name = "CM1 --> HU"
*.cm1.app[0].srcAddr = "0A:00:00:00:05:00"
*.cm1.app[0].destAddr = "0A:00:00:00:07:00"
*.cm1.app[0].startTime = 1us
*.cm1.app[0].period = 16.66ms
*.cm1.app[0].payloadSize = 178500B
*.cm1.app[0].burstSize = 255
*.cm1.app[0].vlanid = 12
*.cm1.app[0].pcp = 3
*.cm1.controller.mac.vlans = [12]
*.cm1.controller.encap.address = "0A:00:00:00:05:00"

# === TLM transmitting applications ===
*.tlm.appCount = 2
*.tlm.app[0].name = "TLM --> HU"
*.tlm.app[0].srcAddr = "0A:00:00:00:09:00"
*.tlm.app[0].destAddr = "0A:00:00:00:07:00"
*.tlm.app[0].startTime = 1us
*.tlm.app[0].period = 625us
*.tlm.app[0].payloadSize = 600B
*.tlm.app[0].burstSize = 1
*.tlm.app[0].vlanid = 15
*.tlm.app[0].pcp = 6
*.tlm.app[1].name = "TLM --> CU"
*.tlm.app[1].srcAddr = "0A:00:00:00:09:00"
*.tlm.app[1].destAddr = "0A:00:00:00:02:00"
*.tlm.app[1].startTime = 1us
*.tlm.app[1].period = 625us
*.tlm.app[1].payloadSize = 600B
*.tlm.app[1].burstSize = 1
*.tlm.app[1].vlanid = 16
*.tlm.app[1].pcp = 6
*.tlm.controller.mac.vlans = [15,16]
*.tlm.controller.encap.address = "0A:00:00:00:09:00"

# === RC transmitting application ===
*.rc.appCount = 1
*.rc.app[0].name = "RC --> HU"
*.rc.app[0].srcAddr = "0A:00:00:00:06:00"
*.rc.app[0].destAddr = "0A:00:00:00:07:00"
*.rc.app[0].startTime = 1us
*.rc.app[0].period = 33.33ms
*.rc.app[0].payloadSize = 178000B
*.rc.app[0].burstSize = 356
*.rc.app[0].vlanid = 17
*.rc.app[0].pcp = 2
*.rc.controller.mac.vlans = [17]
*.rc.controller.encap.address = "0A:00:00:00:06:00"

# === RS1 receiving application ===
*.rs1.appCount = 1
*.rs1.app[0].name = "ME --> RS1"
*.rs1.app[0].srcAddr = "0A:00:00:00:03:00"
*.rs1.controller.encap.address = "0A:00:00:00:08:00"

# === RS2 receiving application ===
*.rs2.appCount = 1
*.rs2.app[0].name = "ME --> RS2"
*.rs2.app[0].srcAddr = "0A:00:00:00:03:00"
*.rs2.controller.encap.address = "0A:00:00:00:08:01"

# === HU receiving applications ===
*.hu.appCount = 4
*.hu.app[0].name = "CU --> HU"
*.hu.app[0].srcAddr = "0A:00:00:00:02:00"
*.hu.app[1].name = "CM1 --> HU"
*.hu.app[1].srcAddr = "0A:00:00:00:05:00"
*.hu.app[2].name = "TLM --> HU"
*.hu.app[2].srcAddr = "0A:00:00:00:09:00"
*.hu.app[3].name = "RC --> HU"
*.hu.app[3].srcAddr = "0A:00:00:00:06:00"
*.hu.controller.encap.address = "0A:00:00:00:07:00"

# === S1 receiving application ===
*.s1.appCount = 1
*.s1.app[0].name = "ME --> S1"
*.s1.app[0].srcAddr = "0A:00:00:00:03:00"
*.s1.controller.encap.address = "0A:00:00:00:04:00"

# === S2 receiving application ===
*.s2.appCount = 1
*.s2.app[0].name = "ME --> S2"
*.s2.app[0].srcAddr = "0A:00:00:00:03:00"
*.s2.controller.encap.address = "0A:00:00:00:04:01"

# === S3 receiving application ===
*.s3.appCount = 1
*.s3.app[0].name = "ME --> S3"
*.s3.app[0].srcAddr = "0A:00:00:00:03:00"
*.s3.controller.encap.address = "0A:00:00:00:04:02"

# === S4 receiving application ===
*.s4.appCount = 1
*.s4.app[0].name = "ME --> S4"
*.s4.app[0].srcAddr = "0A:00:00:00:03:00"
*.s4.controller.encap.address = "0A:00:00:00:04:03"


# === VLAN configuration for the network ===

# === SW1 VLAN ID assignment ===
*.sw1.eth[0].vlans = [1,4,5,7,9,10,13,16]
*.sw1.eth[1].vlans = [1,7,16]
*.sw1.eth[2].vlans = []
*.sw1.eth[3].vlans = []
*.sw1.eth[4].vlans = [3]
*.sw1.eth[5].vlans = [11,12,15,17]
*.sw1.eth[6].vlans = []
*.sw1.eth[7].vlans = []

# === SW2 VLAN ID assignment ===
*.sw2.eth[0].vlans = [3,11,17]
*.sw2.eth[1].vlans = [5,11,13]
*.sw2.eth[2].vlans = []
*.sw2.eth[3].vlans = [1,2,7,8,9,10,16]
*.sw2.eth[4].vlans = []
*.sw2.eth[5].vlans = [4]

# === SW3 VLAN ID assignment ===
*.sw3.eth[0].vlans = [9,11,17]
*.sw3.eth[1].vlans = [1,3,4,7,9,10,16,17]
*.sw3.eth[2].vlans = []
*.sw3.eth[3].vlans = [5]
*.sw3.eth[4].vlans = [13]
*.sw3.eth[5].vlans = []

# === SW4 VLAN ID assignment ===
*.sw4.eth[0].vlans = [1,3,4,5,7,10,13,16]
*.sw4.eth[1].vlans = [3,4,5,9,10,11,13,17]
*.sw4.eth[2].vlans = []
*.sw4.eth[3].vlans = []
*.sw4.eth[4].vlans = [6]
*.sw4.eth[5].vlans = [14]
